FROM damintsew/indexer-idea-2021.2.3-snapshot

COPY 01_first_echo_before.sh /opt/scripts/before_execution
COPY 02_second_echo_before.sh /opt/scripts/before_execution
COPY 01_first_echo_after.sh /opt/scripts/after_execution
COPY 02_second_echo_after.sh /opt/scripts/after_execution
