FROM openkbs/jdk-mvn-py3
#FROM openjdk:17-jdk

ARG INTELLIJ_VERSION
ARG INTELLIJ_IDE_TAR=ideaIU-${INTELLIJ_VERSION}.tar.gz

ENV COMMIT_ID=''
ENV PROJECT_ID=''
ENV IDEA_PROPERTIES=/opt/idea/bin/idea.properties
ENV PROJECT_DIR="/var/project"
#ENV IDEA_PROJECT_DIR="/builds/damintsew1/shared-index-plugin-test/"
ENV SHARED_INDEX_BASE="/shared-index"
#ENV CDN_LAYOUT_TOOL_VERSION=0.8.65

USER root
WORKDIR /opt

RUN apt-get update && apt-get install -y \
    zip \
     && rm -rf /var/lib/apt/lists/*

# Install cdn-layout-tool
#RUN wget https://packages.jetbrains.team/maven/p/ij/intellij-shared-indexes-public/com/jetbrains/intellij/indexing/shared/cdn-layout-tool/${CDN_LAYOUT_TOOL_VERSION}/cdn-layout-tool-${CDN_LAYOUT_TOOL_VERSION}.zip -O cdn-layout-tool.zip && \
#    unzip cdn-layout-tool.zip && \
#    rm cdn-layout-tool.zip && \
#    mv cdn-layout-tool-${CDN_LAYOUT_TOOL_VERSION} cdn-layout-tool

RUN mkdir -p /etc/idea && \
    mkdir -p /etc/idea/config && \
    mkdir -p /etc/idea/log && \
    mkdir -p /etc/idea/system && \
    mkdir ${SHARED_INDEX_BASE} && \
    mkdir ${SHARED_INDEX_BASE}/output && \
    mkdir ${SHARED_INDEX_BASE}/temp

RUN wget https://download-cf.jetbrains.com/idea/${INTELLIJ_IDE_TAR} -nv && \
    tar xzf ${INTELLIJ_IDE_TAR} && \
    tar tzf ${INTELLIJ_IDE_TAR} | head -1 | sed -e 's/\/.*//' | xargs -I{} ln -s {} idea && \
    rm ${INTELLIJ_IDE_TAR} && \
    echo idea.config.path=/etc/idea/config >> /opt/idea/bin/idea.properties && \
    echo idea.log.path=/etc/idea/log >> /opt/idea/bin/idea.properties && \
    echo idea.system.path=/etc/idea/system >> /opt/idea/bin/idea.properties && \
    chmod -R 777 /opt/idea && \
    chmod -R 777 ${SHARED_INDEX_BASE} && \
    chmod -R 777 /etc/idea

COPY run_scripts/run_shared_index.sh .
RUN chmod +x run_shared_index.sh

CMD ./run_shared_index.sh
