FROM openkbs/jdk-mvn-py3

ENV COMMIT_ID=''
ENV PROJECT_ID=''
ENV IDEA_PROPERTIES=/opt/idea/bin/idea.properties
ENV PROJECT_DIR="/var/project"
ENV SHARED_INDEX_BASE="/shared-index"
ENV EXECUTION_SCRIPTS_BEFORE_DIR="/opt/scripts/before_execution"
ENV EXECUTION_SCRIPTS_AFTER_DIR="/opt/scripts/after_execution"

USER root
WORKDIR /opt

RUN apt-get update && apt-get install -y \
    zip \
     && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/scripts && \
    mkdir -p /opt/scripts/before_execution && \
    mkdir -p /opt/scripts/after_execution

RUN mkdir -p /etc/idea && \
    mkdir -p /etc/idea/config && \
    mkdir -p /etc/idea/log && \
    mkdir -p /etc/idea/system && \
    mkdir ${SHARED_INDEX_BASE} && \
    mkdir ${SHARED_INDEX_BASE}/output && \
    mkdir ${SHARED_INDEX_BASE}/temp

ARG INTELLIJ_VERSION
ARG INTELLIJ_IDE_TAR=ideaIU-${INTELLIJ_VERSION}.tar.gz

RUN wget https://download-cf.jetbrains.com/idea/${INTELLIJ_IDE_TAR} -nv && \
    tar xzf ${INTELLIJ_IDE_TAR} && \
    tar tzf ${INTELLIJ_IDE_TAR} | head -1 | sed -e 's/\/.*//' | xargs -I{} ln -s {} idea && \
    rm ${INTELLIJ_IDE_TAR} && \
    echo idea.config.path=/etc/idea/config >> /opt/idea/bin/idea.properties && \
    echo idea.log.path=/etc/idea/log >> /opt/idea/bin/idea.properties && \
    echo idea.system.path=/etc/idea/system >> /opt/idea/bin/idea.properties && \
    chmod -R 777 /opt/idea && \
    chmod -R 777 ${SHARED_INDEX_BASE} && \
    chmod -R 777 /etc/idea

COPY run_scripts/run_shared_index.sh .
COPY run_scripts/utill_scripts/* ${EXECUTION_SCRIPTS_AFTER_DIR}/
RUN chmod +x run_shared_index.sh && \
    chmod +x ${EXECUTION_SCRIPTS_AFTER_DIR}/*

ENTRYPOINT ["bash", "+x", "./run_shared_index.sh"]
