# This is a basic workflow to help you get started with Actions
name: Build Snapshot Docker images for Idea Ultimate

#todo possible improvement https://github.com/docker/build-push-action/blob/master/docs/advanced/share-image-jobs.md

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop, feature/** ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - 'README.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

#      - name: Login to Docker Hub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      # Runs a set of commands using the runners shell
#      - name: Build Docker images for all Intellij Idea Ultimate versions
#        run: |
#          chmod +x ./build/build_ultimate_idea.sh
#          ./build/build_ultimate_idea.sh

      - name: Login to GHCR Hub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Runs a set of commands using the runners shell
      - name: Build Docker images for all Intellij Idea Ultimate versions
        run: |
          chmod +x ./build/build_ultimate_idea.sh
          ./build/build_ultimate_idea.sh -p ghcr.io
