# This is a basic workflow to help you get started with Actions
name: Build Docker images for Intellij Idea ultimate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop, feature/** ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Goland. Build Docker images for all Intellij Idea Ultimate versions
        run: |
          filename='goland_versions.properties' 
          echo Start 
          while read p; do 
            echo "Build imamge for versiont ${p}"
            docker build . --build-arg INTELLIJ_VERSION=goland-${p} --file Dockerfile --tag damintsew/goland-indexer-${p}-snapshot
            
            echo "Push image for versiont goland-indexer-${p}-snapshot"
            docker push damintsew/goland-indexer-${p}-snapshot
          done < "$filename" 
